[plugin]
id = "adi.coolify.ru-RU"
name = "ADI Coolify - Русский"
version = "0.8.4"
type = "translation"
author = "ADI Team"
description = "Russian translations for ADI Coolify plugin"
min_host_version = "0.8.0"

[translation]
translates = "adi.coolify"
language = "ru-RU"
language_name = "Русский"
namespace = "coolify"

[[provides]]
id = "adi.i18n.coolify.ru-RU"
version = "1.0.0"
description = "Russian translations for coolify plugin"

[binary]
name = "adi_coolify_lang_ru"
