[plugin]
id = "adi.coolify.uk-UA"
name = "ADI Coolify - Українська"
version = "0.8.4"
type = "translation"
author = "ADI Team"
description = "Ukrainian translations for ADI Coolify plugin"
min_host_version = "0.8.0"

[translation]
translates = "adi.coolify"
language = "uk-UA"
language_name = "Українська"
namespace = "coolify"

[[provides]]
id = "adi.i18n.coolify.uk-UA"
version = "1.0.0"
description = "Ukrainian translations for coolify plugin"

[tags]
categories = ["i18n", "translation"]

[binary]
name = "plugin"
